SORU:
Merhaba Arkadaşlar;

Yapmak İstediğim; İki Excel dosyasını karşılaştırılarak **Ana_Tablo**daki verileri güncellemek
**Güncel_Kurum_Sayıları** tablosunda olup, **Ana_Tablo**da yoksa olmayan kurumun Ana_tabloya **eklenmesi** ve **Durumu** başlığına **Yeni Açılış (23.03.2024)** olarak not eklenmesi,
**Güncel_Kurum_Sayıları** tablosunda **olmayıp**, **Ana_tablo**da var ise **Ana_tablodan bunların silinmesi** ve mesaj olarak 'silinen kurumun ilçesi ve okul adının (Örnek;‘Sarıca İlçesi-Sarıca İlkokulu Kapatılmıştır’) şeklinde **bildirilmesi**

In [1]:
import pandas as pd
df_ana = pd.read_excel("Ana_Tablo.ods")
df_ana.head()

,KURUM_KODU,KURUM_KODU1,Tipi,İLÇE,KURUM_TÜRÜ,KURUM_ADI,EĞİTİM KADEMESİ,SAYISI,DURUMU
0,4,4.0,RESMİ,SALİHLİ,Anadolu Lisesi,Salihli Anadolu Lisesi,ORTAÖĞRETİM,1,NaN
1,56,56.0,RESMİ,SALİHLİ,İlkokul,Hisar İlkokulu,İLKOKUL,1,NaN
2,3,3.0,RESMİ,SALİHLİ,Anadolu Meslek Programı,Mesleki ve Teknik Anadolu Lisesi,ORTAÖĞRETİM,1,NaN
3,1,1.0,RESMİ,SALİHLİ,İmam Hatip Lisesi,Anadolu İmam Hatip Lisesi,ORTAÖĞRETİM,1,NaN
4,11,11.0,RESMİ,SALİHLİ,Anadolu İmam Hatip Lisesi,Anadolu İmam Hatip Lisesi,ORTAÖĞRETİM,1,NaN

In [2]:
df_guncel = pd.read_excel("Güncel_Kurum_Sayıları.ods")
df_guncel.head()

,KURUM_KODU,KURUM_KODU1,Tipi,İLÇE,KURUM _TÜRÜ,KURUM_ADI,SAYISI,DURUMU
0,4,4.0,RESMİ,SALİHLİ,Anadolu Lisesi,Salihli Anadolu Lisesi,1,NaN
1,3,3.0,RESMİ,SALİHLİ,Anadolu Meslek Programı,Mesleki ve Teknik Anadolu Lisesi,1,NaN
2,1,1.0,RESMİ,SALİHLİ,İmam Hatip Lisesi,Anadolu İmam Hatip Lisesi,1,NaN
3,11,11.0,RESMİ,SALİHLİ,Anadolu İmam Hatip Lisesi,Anadolu İmam Hatip Lisesi,1,NaN
4,72,71.0,RESMİ,SALİHLİ,İlkokul,Narlıdere İlkokulu,1,NaN

In [3]:
df_ana["Kurum_Kod_Ad"] = df_ana["KURUM_KODU"].astype(str) + df_ana["KURUM_ADI"]
df_ana = df_ana.set_index("Kurum_Kod_Ad")
df_ana.head()

,KURUM_KODU,KURUM_KODU1,Tipi,İLÇE,KURUM_TÜRÜ,KURUM_ADI,EĞİTİM KADEMESİ,SAYISI,DURUMU
Kurum_Kod_Ad,,,,,,,,,
4Salihli Anadolu Lisesi,4,4.0,RESMİ,SALİHLİ,Anadolu Lisesi,Salihli Anadolu Lisesi,ORTAÖĞRETİM,1,NaN
56Hisar İlkokulu,56,56.0,RESMİ,SALİHLİ,İlkokul,Hisar İlkokulu,İLKOKUL,1,NaN
3Mesleki ve Teknik Anadolu Lisesi,3,3.0,RESMİ,SALİHLİ,Anadolu Meslek Programı,Mesleki ve Teknik Anadolu Lisesi,ORTAÖĞRETİM,1,NaN
1Anadolu İmam Hatip Lisesi,1,1.0,RESMİ,SALİHLİ,İmam Hatip Lisesi,Anadolu İmam Hatip Lisesi,ORTAÖĞRETİM,1,NaN
11Anadolu İmam Hatip Lisesi,11,11.0,RESMİ,SALİHLİ,Anadolu İmam Hatip Lisesi,Anadolu İmam Hatip Lisesi,ORTAÖĞRETİM,1,NaN

In [4]:
df_guncel["Kurum_Kod_Ad"] = df_guncel["KURUM_KODU"].astype(str) + df_guncel["KURUM_ADI"]
df_guncel = df_guncel.set_index("Kurum_Kod_Ad")
df_guncel.head()

,KURUM_KODU,KURUM_KODU1,Tipi,İLÇE,KURUM _TÜRÜ,KURUM_ADI,SAYISI,DURUMU
Kurum_Kod_Ad,,,,,,,,
4Salihli Anadolu Lisesi,4,4.0,RESMİ,SALİHLİ,Anadolu Lisesi,Salihli Anadolu Lisesi,1,NaN
3Mesleki ve Teknik Anadolu Lisesi,3,3.0,RESMİ,SALİHLİ,Anadolu Meslek Programı,Mesleki ve Teknik Anadolu Lisesi,1,NaN
1Anadolu İmam Hatip Lisesi,1,1.0,RESMİ,SALİHLİ,İmam Hatip Lisesi,Anadolu İmam Hatip Lisesi,1,NaN
11Anadolu İmam Hatip Lisesi,11,11.0,RESMİ,SALİHLİ,Anadolu İmam Hatip Lisesi,Anadolu İmam Hatip Lisesi,1,NaN
72Narlıdere İlkokulu,72,71.0,RESMİ,SALİHLİ,İlkokul,Narlıdere İlkokulu,1,NaN

In [12]:
df_ana_indeks = df_ana.index
df_ana_indeks

Index(['4Salihli Anadolu Lisesi', '56Hisar İlkokulu',
       '3Mesleki ve Teknik Anadolu Lisesi', '1Anadolu İmam Hatip Lisesi',
       '11Anadolu İmam Hatip Lisesi',
       '2Osmanlı Kız Anadolu İmam Hatip Lisesi ',
       '2Osmanlı Kız Anadolu İmam Hatip Lisesi', '8Atatürk İlkokulu',
       '7Atatürk Ortaokulu', '9Sarıca İlkokulu', '5Atatürk İlkokulu',
       '675. Yıl ilkokulu', '55Selam Verdi İlkokulu'],
      dtype='object', name='Kurum_Kod_Ad')

In [13]:
df_guncel_indeks = df_guncel.index
df_guncel_indeks

Index(['4Salihli Anadolu Lisesi', '3Mesleki ve Teknik Anadolu Lisesi',
       '1Anadolu İmam Hatip Lisesi', '11Anadolu İmam Hatip Lisesi',
       '72Narlıdere İlkokulu', '2Osmanlı Kız Anadolu İmam Hatip Lisesi ',
       '2Osmanlı Kız Anadolu İmam Hatip Lisesi', '8Atatürk İlkokulu',
       '7Atatürk Ortaokulu', '9Sarıca İlkokulu', '5Atatürk İlkokulu',
       '675. Yıl ilkokulu', '21Subaşı İlkokulu'],
      dtype='object', name='Kurum_Kod_Ad')

In [15]:
ekle = []

for indeks in df_guncel_indeks:
    if indeks not in df_ana_indeks:
        ekle.append(indeks)

ekle

['72Narlıdere İlkokulu', '21Subaşı İlkokulu']

In [16]:
sil = []

for indeks in df_ana_indeks:
    if indeks not in df_guncel_indeks:
        sil.append(indeks)

sil

['56Hisar İlkokulu', '55Selam Verdi İlkokulu']